const assert=require('node:assert/strict');
const {classify,reviewMove}=require('./review.js'),E=require('./engine.js');
const base={best:0,played:0,before:0,depth:2,tactical:false};
assert.equal(classify({...base,depth:1}),null);
assert.equal(classify(base),null);
assert.equal(classify({...base,played:-160}).mark,'?');
assert.equal(classify({...base,played:-310}).mark,'??');
assert.equal(classify({...base,best:1000000,played:1000000}).mark,'!!');
assert.equal(classify({...base,best:180,played:170,tactical:true}).mark,'!');
assert.equal(classify({...base,forcedDefense:true}).mark,'!');
assert.equal(classify({...base,best:-1000000,played:-1000000}),null);
(async()=>{
 const g=E.createGame();g.board=Array.from({length:10},()=>Array(10).fill(null));g.board[9][0]={type:'K',color:'white'};g.board[0][0]={type:'K',color:'black'};g.board[5][5]={type:'R',color:'white'};g.board[5][7]={type:'P',color:'black',moved:true};g.board[5][9]={type:'R',color:'black'};
 const before=E.copyGame(g);assert.ok(E.move(g,5,5,5,7));
 const frozen=JSON.stringify({board:before.board,history:before.history,turn:before.turn});
 const result=await reviewMove(before,g.history.at(-1),g,{budgetMs:3000});
 assert.ok(result&&['?','??'].includes(result.mark));
 assert.equal(JSON.stringify({board:before.board,history:before.history,turn:before.turn}),frozen);
 assert.equal(await reviewMove(before,g.history.at(-1),g,{shouldCancel:()=>true}),null);
 assert.equal((await reviewMove(before,g.history.at(-1),{...g,winner:'white'})).mark,'!');
 console.log('Passed: conservative annotations, all four symbols, poisoned capture, non-mutating analysis, cancellation and winning move.');
})().catch(e=>{console.error(e);process.exitCode=1;});